default:
  image: rust:alpine3.13
  before_script:
    - apk add --no-cache alpine-sdk glib-dev pango-dev gdk-pixbuf-dev gtk+3.0-dev
    - rustc --version
    - cargo --version
  tags:
    - shared-fi

stages:
  - build
  - test

build:
  stage: build
  script:
    - cargo build --verbose

lint:
  stage: test
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check
    - rustup component add clippy
    - cargo clippy -- -D warnings

test:
  stage: test
  timeout: 10 minutes
  script:
    - cargo test --verbose

